language: node_js

node_js:
  - "iojs"
  - "8"

before_install:
  - npm install -g npm@2.14.5
  - npm install -g grunt-cli cordova ionic

services:
  - mongodb

script:
  - npm install

cache:
  directories:
    - "node_modules"
