language: node_js

node_js:
  - "8"

before_install:
  - npm install -g npm@2.14.5
  - npm install -g ionic cordova
  - npm install

services:
  - mongodb

script:
  - ionic coredova build ios

cache:
  directories:
    - "node_modules"
